---
title: Mapgive
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: MapGive
baseurl: "/Mapgive"
destination: temp/
twitter_username: MapGive
permalink: none
future: true
exclude:
- ".DS_Store"
- ".git"
- ".gitignore"
- ".vagrant"
- Gruntfile.js
- Vagrantfile
- package.json
- node_modules
- backups
- _assets/img/src-images
